---
# roles/reprepro/tasks/reprepro.yml

- name: be sure reprepro is installed
  apt: pkg={{ item }} state=latest
  with_items:
    - reprepro
  tags:
    - reprepro
    - packages

- name: be sure configration directories are prpared
  file: path=/home/{{ reprepro_user }}/{{ item }} owner={{ reprepro_user }} group={{ reprepro_group }} mode=0700 state=directory
  with_items:
    - .gnupg
    - .ssh
  tags:
    - configuration
    - reprepro

- name: be sure configuraton files are prepared
  template: src={{ item }}.j2 dest=/home/{{ reprepro_user }}/.gnupg/{{ item }} owner={{ reprepro_user }} group={{ reprepro_group }} mode=0600
  with_items:
    - gpg.conf
  tags:
    - configuration
    - gnupg
    - reprepro

#- name: be sure configuraton files are prepared
#  copy: src={{ item }} dest=/home/{{ reprepro_user }}/.gnupg/{{ item }} owner={{ reprepro_user }} group={{ reprepro_group }} mode=0600
#  with_items:
#    - pubring.gpg
#    - secring.gpg
#    - trustdb.gpg
#  tags:
#    - configuration
#    - gnupg
#    - reprepro

#- name: be sure configuration files are prepared
#  copy: src={{ item }} dest=/home/{{ reprepro_user }}/.ssh/{{ item }} owner={{ reprepro_user }} group={{ reprepro_group }} mode=0600
#  with_items:
#    - authorized_keys
#  tags:
#    - configuration
#    - ssh
#    - reprepro

- name: check local archive directory
  file: path={{ item }} owner={{ reprepro_user }} group={{ reprepro_group }} state=directory mode=0755 recurse=yes
  with_items:
    - /var/www/ubuntu-custom
    - /var/www/debian-custom
    - /var/lib/debpkg-custom
    - /var/lib/debpkg-custom/debian
    - /var/lib/debpkg-custom/ubuntu
  tags:
    - reprepro

- name: symlink of pool/dist for publish
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  with_items:
    - { src: "/var/lib/debpkg-custom/ubuntu/pool", dest: "/var/www/ubuntu-custom/pool" }
    - { src: "/var/lib/debpkg-custom/ubuntu/dists", dest: "/var/www/ubuntu-custom/dists" }
    - { src: "/var/lib/debpkg-custom/debian/pool", dest: "/var/www/debian-custom/pool" }
    - { src: "/var/lib/debpkg-custom/debian/dists", dest: "/var/www/debian-custom/dists" }
  tags:
    - reprepro
    - apache

- name: be sure reprepro conf directory is present
  file: path=/var/lib/debpkg-custom/{{ item.distro_name }}/conf owner={{ reprepro_user }} group={{ reprepro_group }} state=directory recurse=yes
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure reprepro incoming directory is present
  file: path=/var/lib/debpkg-custom/{{ item.distro_name }}/incoming owner={{ reprepro_user }} group={{ reprepro_group }} state=directory recurse=yes
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure incoming file is present
  template: src=incoming.j2 dest=/var/lib/debpkg-custom/{{ item.distro_name }}/conf/incoming owner={{ reprepro_user }} group={{ reprepro_group }} mode=0644
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure distributions file is present
  template: src=distributions.j2 dest=/var/lib/debpkg-custom/{{ item.distro_name }}/conf/distributions owner={{ reprepro_user }} group={{ reprepro_group }} mode=0644
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure options file is present
  template: src=options.j2 dest=/var/lib/debpkg-custom/{{ item.distro_name }}/conf/options owner={{ reprepro_user }} group={{ reprepro_group }} mode=0644
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

#- name: be sure public key of local archives/custom repositoryies is prepared
#  copy: src={{ item }} dest=/var/www/ owner=root group=root mode=0644
#  with_items:
#    - "{{ reprepro_user }}.pubkey"
#    - "{{ reprepro_user }}.pubkey.sha512"
#  tags:
#    - publickey
#    - apache
