---
# roles/reprepro/tasks/reprepro.yml

- name: be sure reprepro is installed
  apt: pkg={{ item }} state=latest
  with_items:
    - reprepro
  tags:
    - reprepro
    - packages

- name: be sure group 'reprepro group' is prepared
  group: name={{ reprepro_gid }} gid={{ reprepro_gidnumber }} state=present
  tags:
    - group

- name: be sure user 'reprepro user' is prepared
  user: name={{ reprepro_uid }} uid={{ reprepro_uidnumber }} createhome=yes group={{ reprepro_gid }} state=present
  tags:
    - user


- name: be sure configration directories are prpared
  file: path=/home/{{ reprepro_uid }}/{{ item }} owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0700 state=directory
  with_items:
    - .gnupg
    - .ssh
  tags:
    - configuration
    - reprepro

#- name: be sure configuraton file are prepared
#  template: src={{ item }}.j2 dest=/home/{{ reprepro_uid }}/.gnupg/{{ item }} owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0600
#  tags:
#    - configuration
#    - gnupg
#  with_items:
#    - gpg.conf

#- name: be sure keyring files are prepared
#  copy: src={{ item }} dest=/home/{{ reprepro_uid }}/.gnupg/{{ item }} owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0600
#  tags:
#    - configuration
#    - gnupg
#  with_items:
#    - pubring.gpg
#    - secring.gpg
#    - trustdb.gpg

#- name: be sure configuration files are prepared
#  copy: src={{ item }} dest=/home/{{ reprepro_uid }}/.ssh/{{ item }} owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0600
#  with_items:
#    - authorized_keys
#  tags:
#    - configuration
#    - ssh
#    - reprepro

- name: check local archive directory
  file: path={{ item }} owner={{ rerepro_uid }} group={{ reprepro_gid }} state=directory mode=0755 recurse=yes
  with_items:
    - /var/www/ubuntu-custom
    - /var/www/debian-custom
    - /var/lib/debpkg-custom
    - /var/lib/debpkg-custom/debian
    - /var/lib/debpkg-custom/debian/conf
    - /var/lib/debpkg-custom/debian/incoming
    - /var/lib/debpkg-custom/ubuntu
    - /var/lib/debpkg-custom/ubuntu/conf
    - /var/lib/debpkg-custom/ubuntu/incoming
  tags:
    - reprepro

- name: symlink of pool/dist for publish
  file: src={{ item.src }} dest={{ item.dest }} state=link force=yes
  with_items:
    - { src: "/var/lib/debpkg-custom/ubuntu/pool", dest: "/var/www/ubuntu-custom/pool" }
    - { src: "/var/lib/debpkg-custom/ubuntu/dists", dest: "/var/www/ubuntu-custom/dists" }
    - { src: "/var/lib/debpkg-custom/debian/pool", dest: "/var/www/debian-custom/pool" }
    - { src: "/var/lib/debpkg-custom/debian/dists", dest: "/var/www/debian-custom/dists" }
  tags:
    - reprepro
    - apache

- name: be sure incoming file is present
  template: src=incoming.j2 dest=/var/lib/debpkg-custom/{{ item.distro_name }}/conf/incoming owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0644
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure distributions file is present
  template: src=distributions.j2 dest=/var/lib/debpkg-custom/{{ item.distro_name }}/conf/distributions owner={{ reprepro_uid }} group={{ reprepro_gid }} mode=0644
  with_items:
    - { distro_name: "ubuntu", codenames: ["precise", "trusty"] }
    - { distro_name: "debian", codenames: ["wheezy"] }
  tags:
    - reprepro

- name: be sure options file is present
  template: src=options.j2 dest=/var/lib/debpkg-custom/{{ item }}/conf/options owner={{ rerepro_uid }} group={{ reprepro_gid }} mode=0644
  with_items:
    - ubuntu
    - debian
  tags:
    - reprepro
