---
# file: roles/webtier/tasks/apache.yml

- name: be sure packages is prepared
  apt: name={{ item }} state=latest
  with_items:
    - apache2-mpm-event
  tags:
    - packages

- name: be sure servername is prepared
  copy: src=servername.conf dest=/etc/apache2/conf-available/servername.conf owner=root 
group=root mode=0644
  tags:
    - apache
  notify:
    - reload apache

- name: be sure servername is enabled
  command: a2enconf servername
  notify:
    - reload apache
  tags:
    - apache

- name: be sure /var/www/html directory is removed
  file: path=/var/www/html state=absent
  tags:
    - apache

#- name: be sure public key of local archives/custom repositoryies is prepared
#  copy: src={{ item }} dest=/var/www/ owner=root group=root mode=0644
#  with_items:
#    - repo.pubkey
#    - repo.pubkey.sha512
#  tags:
#    - publickey
#    - apache

- name: be sure site file is configured
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf backup=yes
  notify: reload apache2
  tags:
    - apache
